apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.python.name }}
  labels:
    {{- include "button.labels" . | nindent 4 }}
spec:
  type: {{ .Values.python.service.type }}
  ports:
    - port: {{ .Values.python.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.python.name }}
