ingress:
  enabled: true
  className: nginx # run `kubectl get ingressclass` and use the value form there
  annotations: 
     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
     cert-manager.io/cluster-issuer: letsencrypt-prod # use the value from `kubectl get clusterissuer`
  hosts:
    - host: jacoh.k8s-course.co.za # this one you'll know by now
      paths:
        - path: /
          pathType: Prefix
          service:
            name: nginx
            port: 80
        - path: /api # add your prefix here for the backend
          pathType: Prefix
          service:
            name: python-service # your backend service name
            port: 5000 # what port do you want to forward traffic on your backend?
  tls: 
   - secretName: nginx-tls-secret
     hosts:
       - jacoh.k8s-course.co.za
imagePullSecrets:
  - name: your-regcred
nginx:
  image:
    repository: harbor.jacoh.k8s-course.co.za/application/nginx
    tag: v4
  replicaCount: 1
  name: nginx
  serverName: jacoh.k8s-course.co.za
  rootPath: "/usr/share/nginx/html"
  mountPath: "/etc/nginx/conf.d"
  indexFiles:
    - "index.html"
    - "index.htm"
  service:
    type: ClusterIP
    port: 80

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi 
python:
  image:
    repository: harbor.jacoh.k8s-course.co.za/application/python
    tag: v2
  name: nginx
  name: python
  envs:
    - name: DB_HOST
      value: "postgresql.default.svc.cluster.local" 
    - name: DB_NAME
      value: dbname
    - name: DB_USER
      value: youruser
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
  service: 
    type: ClusterIP
    port: 5000